def analogRead(pin): ...
def analogWrite(pin, duty) -> None: ...
def digitalWrite(pin, value) -> None: ...
def digitalRead(pin): ...
def toggleIO(pin) -> None: ...
def map_value(value, input_min, input_max, aims_min, aims_max): ...
