from typing import Any

class M5mqtt:
    mqtt: Any
    topic_callback: Any
    mqttState: bool
    ping_out_time: Any
    def __init__(self, client_id, server, port, user: Any | None = ..., password: Any | None = ..., keepalive: int = ...) -> None: ...
    def on_connect(self) -> None: ...
    def start(self) -> None: ...
    def subscribe(self, topic, callback) -> None: ...
    def unsubscribe(self, topic) -> None: ...
    def publish(self, topic, data) -> None: ...
