from m5stack import btnB as btnB
from typing import Any

wlan_sta: Any

def screenShow() -> None: ...
def reconnect(block: bool = ...): ...
def doConnect(ntwrk_ssid, netwrk_pass, lcdShow: bool = ...): ...
def autoConnect(lcdShow: bool = ...): ...
def saveWiFi(ssid, password) -> None: ...
def isconnected(): ...
